### ISSUE TITLE
crash on Android M

### ISSUE THREAD

**Issue by iceberg1369** [cernekee/ics-openconnect#7]
application throws an error on Android M
java.lang.UnsatisfiedLinkError: libopenconnect.so has text relocations
even compiling with NDK10e could not resolve the issue

**Comment by magicbane** [comment]
I'm currently using nexus 5X with no problems? Is this still an issue?

**Comment by iceberg1369** [comment]
I think .so files for apk should be updated cause they have TEXT_RELOCATIONS and furthermore openssl version of libs are old, therefore I think there should be a new makefile released for future compatibility

**Comment by cernekee** [comment]
Right, it should only show up when you bump the target SDK version in the manifest to >= M.  The new check in Bionic is [here](https://android.googlesource.com/platform/bionic/+/e4ad91f86a47b39612e030a162f4793cb3421d31%5E%21/#F0).

It would be good to fix this upstream since that is where the Android Makefile comes from:

http://git.infradead.org/users/dwmw2/openconnect.git/blob/HEAD:/android/Makefile

BTW, the app uses GnuTLS instead of OpenSSL (but you can switch between the two by tweaking the Makefile).  GnuTLS 3.2.21 is two major revs behind the current stable branch.

**Comment by magicbane** [comment]
Hmm. Yeah I noticed that it's still using sha1 cipher suites. I was
thinking of updating it as well, but haven't gotten the time for it yet.

**Comment by moralrebuild** [comment]
@iceberg1369 Have you get this issue fixed? It drives me crazy for a year and now I have to switch to Cisco AnyConnect Mobile client which I hate to use.
